### ISSUE TITLE
4 Elaborate website requirements

### ISSUE THREAD

**Issue by monasobh** [monasobh/WebDocs-Assignment-Group-1#2]
Make a list of all webpages. Including at least 7/ 10/13 webpages for a team of 1/2/3 members, and at most 20. For each planned webpage provide

        a file name,

        a title (for the title element),

        a description of the text and pictures/images to include, and

        a description of the functionality, if pertinent.

    This list of four columns should be delivered in the form of a table in an HTML file.

    Make a website design diagram. Specify the website's views, areas and pages using the method described in the lecture slides about Website Design. Create the website design diagram using [Balsamiq](https://www.balsamiq.com/), a tool for creating wireframes online and collaboratively, and that allows you to export your design to PDF format files.

    Make sure to include 2/3/4 of the following items for a team of 1/2/3 members on your website:

        a page based on an XML data file, such as an address list or a product list,

        one or more SVG images, such as a logo, icons, decorative graphics, etc.,

        audio or video files or web links to streaming services. Find instructions for embedding [YouTube](https://support.google.com/youtube/answer/171780?hl=en), [Twitch](https://dev.twitch.tv/docs/embed), [Vimeo](https://vimeo.zendesk.com/hc/en-us/articles/224969968-Embedding-videos-overview), [SoundCloud](https://help.soundcloud.com/hc/en-us/articles/115003566828-The-Visual-embedded-player-), [Spotify](https://developer.spotify.com/documentation/widgets/generate/embed/), [Deezer](https://widget.deezer.com/), etc.

    Elaborate visual style. Delineate how the website should look and feel: colors, fonts, layout, decorative elements, etc.

**Comment by bauscha** [comment]
- webpages-list done
