### ISSUE TITLE
Add as contributor

### ISSUE THREAD

**Issue by robinmdm** [monasobh/WebDocs-Assignment-Group-1#5]
Hello,

Kindly add us as contributors to the development of your website.

Here are the GitHub profile names:
robinmdm
chrir0
coast-moonlight

Thanks!

**Comment by monasobh** [comment]
Hi, we just added you as collaboratiors. If you have any question, please let us know.
All the best.

**Comment by robinmdm** [comment]
If I am not wrong, we are the developer of your project. And your project is this Salsa Swing School, right?

**Comment by monasobh** [comment]
Yes, you are our developers. Our project is called Salsa Swings Dance Studio as you can read on the Readme.md :)
