### ISSUE TITLE
HTML Issues

### ISSUE THREAD

**Issue by chrir0** [monasobh/WebDocs-Assignment-Group-1#7]
If manageable, please fix these issues until the deadline @robinmdm, thank you in advance.

Social Media Icons are too big, please scale them down. Also if possible, make them one-colored (e.g. all Icons black)

courses.html -> Use the images of the detail pages in the overview

Our URL is supposed to be "Salsa-swings", currently it's "Salsa-swing"

**Comment by robinmdm** [comment]
I fixed the domain name issue.
 The rest I will work on that and fix the issues.
 
 And, please finish the CSS issues.

Thanks.

**Comment by robinmdm** [comment]
facebook: https://freeicons.io/social-media-icons-5/facebook-black-icon-15755

instagram: https://freeicons.io/social-media-icons-5/instagram-black-icon-15770

twitter: https://freeicons.io/social-media-icons-5/twitter-black-icon-15829

these are the icons from this website, now there are lot of sizes, and all icons are in black. I am confused about the size.
